# Generated by Django 5.1.5 on 2025-03-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_event_organizer_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/default_event.jpg', upload_to='event_images/'),
        ),
    ]
