# Generated by Django 5.1.7 on 2025-03-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_initial'),
        ('eventapp', '0006_alter_event_image_alter_event_time'),
    ]

    operations = [
    ]
