# Generated by Django 5.1.7 on 2025-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
